

in_zip: 
  hippunfold: '/project/6050199/akhanf/ext-bids/developing_human_connectome/deriv/hippunfold_v1.2.1_synthseg_dHCP_neonatal.zip'



#get desc-nnunet_dseg.nii.gz images from hippunfold as lbl, and T1w as input img
hippunfold_lbl: '/project/6050199/akhanf/ext-bids/developing_human_connectome/deriv/neonate_dseg_manually_corrected/sub-{subject}_hemi-{hemi}_space-corobl_desc-postproc_dseg.nii.gz'


dataset_json:
  name: HippDHCP
  description: dHCP manually-corrected dataset for hippunfold
  reference: Western University
  license: CC-BY-SA 4.0
  release: 0.1
  tensorImageSize: 3D
  modality:
    '0': T1
  labels:
   "0": "background"
   "1": "GM"
   "2": "SRLM"
   "3": "MTLC"
   "4": "Pial"
   "5": "HATA"
   "6": "IndGris"
   "7": "Cyst"
   "8": "DG"
  numTraining: 0
  numTest: 0
  training: []
  test: []
  


out_resolution: '128x256x128'
task: Task301_dhcp_T1w_synthseg_manuallycorrected
trainer: nnUNetTrainer
plans: nnUNetPlansv2.1
architecture: 3d_fullres
checkpoint: checkpoint_best #or checkpoint_final

nnunet_env:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: 'preprocessed'
  RESULTS_FOLDER: 'trained_models'

nnunet_env_tmp:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: '$TMPDIR/preprocessed'
  RESULTS_FOLDER: 'trained_models'

