

in_zip: 
  hippunfold: /home/ROBARTS/alik/graham/ext-bids/developing_human_connectome/deriv/hippunfold_v1.2.1_synthseg_dHCP_neonatal.zip



#get desc-nnunet_dseg.nii.gz images from hippunfold as lbl, and T1w as input img
hippunfold_img: '../hippunfold_T1w_model-b1000_newatlas/work/sub-{subject}/anat/sub-{subject}_hemi-L_space-corobl_desc-cropped_T1w.nii.gz'
hippunfold_lbl: '/home/ROBARTS/alik/graham/ext-bids/developing_human_connectome/deriv/neonate_dseg_manually_corrected/sub-{subject}_hemi-{hemi}_space-corobl_desc-postproc_dseg.nii.gz'


dataset_json:
  name: HippDHCP
  description: dHCP manually-corrected dataset for hippunfold
  reference: Western University
  license: CC-BY-SA 4.0
  release: 0.1
  tensorImageSize: 3D
  channel_names:
    '0': T1
  labels:
    background: 0
    GM: 1
    SRLM: 2
    MTLC: 3
    Pial: 4
    HATA: 5
    IndGris: 6
    Cyst: 7
    DG: 8
  file_ending: .nii.gz
  numTraining: 0
  numTest: 0
  training: []
  test: []
  



out_resolution: '128x256x128'
dataset: Dataset301_dhcp_T1w_synthseg_manuallycorrected 
trainer: nnUNetTrainer
plans: nnUNetPlans
architecture: 3d_fullres
checkpoint: checkpoint_best #or checkpoint_final

nnunet_env:
  nnUNet_raw: 'raw_data'
  nnUNet_preprocessed: 'preprocessed'
  nnUNet_results: 'trained_models'

nnunet_env_tmp:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: '$TMPDIR/preprocessed'
  nnUNet_results: 'trained_models'

